import type { Metadata } from "next";
import { metropolis } from "./ui/fonts";
import "./globals.css";



export const metadata: Metadata = {
  title: "pulse-hospital",
  description: "Generated by pulse-point",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${metropolis.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
